version: "2.2"

#docker run --gpus all -it --privileged --ipc=host -v ${HOST_DIR}:${CONTAINER_DIR}:rw -v /tmp/.X11-unix:/tmp/.X11-unix:rw -v /usr/share/nvidia:/usr/share/nvidia --env="DISPLAY" --runtime=nvidia --name=${CONTAINER_NAME} depth-optimizer_dope:humble-v1 bash

services:
  dope_depth_opt:
    container_name: "dope_depth_opt_compose"
    network_mode: host 
    runtime: nvidia
    image: depth-optimizer_dope:humble-v1
    privileged: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev/bus/usb:/dev/bus/usb
      - /usr/share/nvidia:/usr/share/nvidia
      - ..:/root/ros2ws/src/depth_optimization
    tty: true
    stdin_open: true
    environment:
      - NVIDIA_VISIBLE_DEVICES=all 
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/tmp/xauth/.docker.xauth  
      - NVIDIA_DRIVER_CAPABILITIES=graphics,video,utility
      - TERM=xterm
    device_cgroup_rules:
      - "c 189:* rmw"
    devices:
      - /dev/dri:/dev/dri
      - /dev/snd:/dev/snd
      - /dev/bus/usb:/dev/bus/usb:rw
    # command: >
    #   bash -c "echo source /opt/ros/humble/setup.bash >> /root/.bashrc &&
    #    echo source ~/ws/install/setup.bash >> /root/.bashrc"
